sudo: false
addons:
  apt:
    packages:
    - libgeos-dev
    - libproj-dev
language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1
  - 2.2
  - 2.3.0
  - jruby-1.7
  - jruby-9.0.4.0
  - rbx-2
matrix:
  allow_failures:
    rvm: rbx-2
